apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-from-yaml-prod
  namespace: argocd 
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: prod 
    repoURL: https://github.com/rohithaus/argocd-nana.git
    targetRevision: HEAD 